#	Makefile for unit Hydro/HydroMain/Spark
Hydro += Hydro_data.o Hydro_init.o Hydro_computeDt.o \
	hy_rk_getFaceFlux.o hy_rk_interface.o \
	hy_rk_updateSoln.o Hydro_correctGravSrc.o \
	hy_rk_getGravAccel.o hy_rk_correctFluxes.o hy_data.o\
	hy_riemann.o  hy_prim2con.o hy_prim2flx.o
