#	Makefile for unit Hydro/HydroMain/Spark
Hydro += Hydro_data.o Hydro_init.o Hydro_computeDt.o \
	hy_rk_getFaceFlux.o hy_rk_interface.o \
	hy_rk_updateSoln.o Hydro_correctGravSrc.o \
	hy_rk_getGravAccel.o hy_rk_correctFluxes.o hy_data.o hy_manageScr.o\
	hy_riemann.o hy_reconstruct.o prim2con.o prim2flx.o
