# Makefile for Weaklib equation of state

Eos += eos_wlData.o \
       eos_weaklibInit.o \
       eos_weaklib_inter.o \
       eos_weaklib.o \
       Eos_wlInterface.o \
       Eos_wlEnerShift.o \
       Eos_wlOneZone.o

Eos += Eos_wlInterface.o \
       Eos_wlDetectBounce.o

