Stencils += Stencils_interface.o \
            Stencils_init.o \
            Stencils_finalize.o

Stencils += Stencils_advectWeno.o \
            Stencils_advectCentral.o \
            Stencils_cnt_advectUpwind2d.o \
            Stencils_cnt_advectUpwind3d.o

Stencils += Stencils_diffusion.o 

Stencils += Stencils_lsRedistance2d.o \
            Stencils_lsRedistance3d.o \
            Stencils_lsFaceProps2d.o \
            Stencils_lsFaceProps3d.o \
            Stencils_lsCenterProps.o \
            Stencils_lsNormals2d.o \
            Stencils_lsNormals3d.o \
            Stencils_lsCurvature2d.o \
            Stencils_lsCurvature3d.o

Stencils += Stencils_integrateEuler.o \
            Stencils_integrateAB2.o
