[dr_iter_getBaseVals]
definition =
 call itor%%currentTile(tileDesc)
         call tileDesc%%deltas(del)
         nullify(solnData)
         call tileDesc%%getDataPtr(solnData, CENTER)
         blkLimits=tileDesc%%limits
	 blkLimitsGC=tileDesc%%blkLimitsGC

[dr_getFacePnt]
definition=
         nullify(facexData, faceyData, facezData)
         call tileDesc%%getDataPtr(facexData, FACEX)
         call tileDesc%%getDataPtr(faceyData, FACEY)
 #if NDIM == 3
         call tileDesc%%getDataPtr(facezData, FACEZ)
 #endif


[dr_iter_releaseBase]
definition =
         call tileDesc%%releaseDataPtr(solnData, CENTER)
         call itor%%next()


[dr_releaseFacePnt]
definition = 
        call tileDesc%%releaseDataPtr(facexData, FACEX)
         call tileDesc%%releaseDataPtr(faceyData, FACEY)
 #if NDIM ==3
         call tileDesc%%releaseDataPtr(facezData, FACEZ)
 #endif
         !---------------------------------------------------------

[dr_mapLimits]
definition =
  lo(:) = blkLimits(LOW,:)-blkLimitsGC(LOW,:)+1
  hi(:) = blkLimits(HIGH,:)-blkLimits(LOW,:)+lo(:)




 