Orchestration += Orchestration_init.o \
		         Orchestration_finalize.o \
		         Orchestration_interfaceTypeDecl.o \
		         Orchestration_interface.o \
		         Orchestration_checkInternalError.o \
		         Orchestration_setupPipelineForCpuTasks.o \
		         Orchestration_setupPipelineForGpuTasks.o \
		         Orchestration_setupPipelineForExtGpuTasks.o \
		         Orchestration_pushTileToPipeline.o \
		         Orchestration_pushTileToGpuPipeline.o \
		         Orchestration_pushTileToExtGpuPipeline.o \
		         Orchestration_teardownPipelineForCpuTasks.o \
		         Orchestration_teardownPipelineForGpuTasks.o \
		         Orchestration_teardownPipelineForExtGpuTasks.o \
		         Orchestration_executeTasks_Cpu.o \
		         Orchestration_executeTasks_Gpu.o

