Orchestration += Orchestration_init.o \
		         Orchestration_finalize.o \
		         Orchestration_interface.o \
		         Orchestration_checkInternalError.o \
		         Orchestration_executeTasks_Cpu.o \
		         Orchestration_executeTasks_Gpu.o

