Orchestration += Orchestration_init.o \
		         Orchestration_finalize.o \
		         Orchestration_interfaceTypeDecl.o \
		         Orchestration_interface.o \
		         Orchestration_checkInternalError.o \
		         Orchestration_setupPipelineForCpuTasks.o \
		         Orchestration_pushTileToPipeline.o \
		         Orchestration_teardownPipelineForCpuTasks.o \
		         Orchestration_executeTasks_Cpu.o \
		         Orchestration_executeTasks_Gpu.o

