!! @copyright Copyright 2024 UChicago Argonne, LLC and contributors
!!
!! @licenseblock
!! Licensed under the Apache License, Version 2.0 (the "License");
!! you may not use this file except in compliance with the License.
!!
!! Unless required by applicable law or agreed to in writing, software
!! distributed under the License is distributed on an "AS IS" BASIS,
!! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
!! See the License for the specific language governing permissions and
!! limitations under the License.
!! @endlicenseblock
!!
!! @file

!> @ingroup OrchestrationMilhoja
!! @stubref{Orchestration_setupPipelineForCpuGpuTasks}
!!
!! @brief Stub implementation of Orchestration_setupPipelineForCpuGpuTasks
!!
!! @details
!! Set up the orchestration runtime so that it is ready to execute the given
!! task function with either the CPU/GPU or the Split CPU/GPUthread team
!! configuration.  Upon successful completion of the setup, the orchestration
!! runtime will be ready to accept data items (tiles) pushed to it for
!! execution with Orchestration_pushTileToGpuGpuPipeline or
!! Orchestration_pushTileToGpuGpuSplitPipeline calls.
!! To end the cycle, a call to Orchestration_setupPipelineForCpuGpuTasks has
!! to be matched with an Orchestration_teardownPipelineForCpuGpuTasks or an
!! Orchestration_teardownPipelineForCpuGpuSplitTasks call.
!!
!! @note
!! An actual, non-stub implementation of this interface is only available if
!! (1) Flash-X is linked with a Milhoja library that was configured to support
!! datapackets and (2) Flash-X was configured with a "Milhoja" setup variable
!! that requests such an implementation, such as Milhoja="...,CUDA,..." or
!! Milhoja="...,HOSTMEM,...". The latter is also known as "specifying a
!! GPU-compatible runtime backend".
!!
!! @param MH_pktTaskFunction    The task function to be executed by the "GPU"
!!                              thread team.  It is assumed that this function
!!                              was written to launch kernels on GPUs.
!!                              Task functions generally are wrappers around
!!                              invocations of one or several user-provided
!!                              routines (such as "static Fortran routines"),
!!                              generated by CGKIT and available to callers of
!!                              the Orchestration interface by lines such as,
!!                              for example,
!!                                use gpu_tf_hydro_mod,ONLY: gpu_tf_hydro_Cpp2C
!!                              in the case of orchestrating a task for a
!!                              Hydro operation.
!! @param nThreads              The number of threads to activate in the teams
!!                              that applies the task functions.
!! @param nTilesPerPacket       The maximum number of tiles allowed in each
!!                              datapacket.
!! @param MH_pktProto_Cptr        Pointer to a prototype datapacket, from which
!!                              the orchestration runtime will generate new
!!                              datapackets.
!!                              Prototype datapackets are created by calling
!!                              a function like, for example,
!!                              instantiate_gpu_tf_hydro_packet_C in the case
!!                              of orchestrating work for a Hydro operation.
subroutine Orchestration_setupPipelineForCpuGpuTasks(MH_pktTaskFunction, &
                                          MH_tileTaskFunction,     &
                                          nThreads,            &
                                          nTilesPerPackety,     &
                                          MH_pktProto_Cptr,    &
                                          nTilesPerCpuTurn)
    use iso_c_binding, ONLY : C_PTR

    use Orchestration_interfaceTypeDecl, ONLY : milhoja_runtime_taskFunction

    implicit none

    procedure(milhoja_runtime_taskFunction)            :: MH_pktTaskFunction
    procedure(milhoja_runtime_taskFunction)            :: MH_tileTaskFunction
    integer,                                intent(IN) :: nThreads
    integer,                                intent(IN) :: nTilesPerPacket
    type(C_PTR),                            intent(IN) :: MH_pktProto_CPtr
    integer,OPTIONAL,                       intent(IN) :: nTilesPerCpuTurn
end subroutine Orchestration_setupPipelineForCpuGpuTasks

