!> @copyright Copyright 2024 UChicago Argonne, LLC and contributors
!!
!! @licenseblock
!! Licensed under the Apache License, Version 2.0 (the "License");
!! you may not use this file except in compliance with the License.
!!
!! Unless required by applicable law or agreed to in writing, software
!! distributed under the License is distributed on an "AS IS" BASIS,
!! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
!! See the License for the specific language governing permissions and
!! limitations under the License.
!! @endlicenseblock
!!
!! @file

#include "Simulation.h"

!> @ingroup OrchestrationMilhoja
!! @stubref{Orchestration_executeTasks_CpuGpuSplit}
!!
!! @brief Stub implementation of Orchestration_executeTasks_CpuGpuSplit
!!
!! @note
!! The MH_pktTaskFunction and MH_tileTaskFunction should generally refer to
!! implementations of "the same" numerical functionality when a CPU/GPU Split
!! thread team configuration is used. That is because some tiles will get
!! processed by the tile task function on a CPU, other tiles by the packet
!! task function (as part of a datapacket) "on a GPU", and the validity of
!! any user algorithm should not depend on which gets processed where.
!!
!! @param MH_pktTaskFunction    The task function to be executed by the "GPU"
!!                              thread team.  It is assumed that this function
!!                              was written to launch kernels on GPUs.
!!                              Task functions generally are wrappers around
!!                              invocations of one or several user-provided
!!                              routines (such as "static Fortran routines"),
!!                              generated by CGKIT and available to callers of
!!                              the Orchestration interface by lines such as,
!!                              for example,
!!                                use gpu_tf_hydro_mod,ONLY: gpu_tf_hydro_Cpp2C
!!                              in the case of orchestrating a task for a
!!                              Hydro operation.
!! @param MH_tileTaskFunction    The task function to be executed by the "CPU"
!!                              thread team.  It is assumed that this function
!!                              was written to execute kernels on CPUs.
!!                              Task functions generally are wrappers around
!!                              invocations of one or several user-provided
!!                              routines (such as "static Fortran routines"),
!!                              generated by CGKIT and available to callers of
!!                              the Orchestration interface by lines such as,
!!                              for example,
!!                                use cpu_tf_hydro_mod,ONLY: cpu_tf_hydro_Cpp2C
!!                              in the case of orchestrating a task for a
!!                              Hydro operation.
!! @param nDistributorThreads   The number of threads in a multithreaded distributor.
!!                              This functionality may be unimplemented or untested.
!!                              The recommended value is 1.
!! @param nThreads              The number of threads to activate in the teams
!!                              that applies the task functions.
!! @param nTilesPerPacket       The maximum number of tiles allowed in each
!!                              datapacket.
!! @param nTilesPerCpuTurn      This should be a positive integer; it determines,
!!                              for the Split CPU/GPU bundle, how many tiles
!!                              should be enqueued separately to the CPU team
!!                              before beginning to fill the next datapacket
!!                              (with the next nTilesPerPacket tile that are
!!                              pushed) for enqueueing to the GPU team.
!! @param MH_packet_Cptr        Pointer to a prototype datapacket, from which
!!                              the orchestration runtime will generate new
!!                              datapackets.
!!                              Prototype datapackets are created by calling
!!                              a function like, for example,
!!                              instantiate_gpu_tf_hydro_packet_C in the case
!!                              of orchestrating work for a Hydro operation.
!! @param MH_tileProto_Cptr     Pointer to a prototype tile wrapper object, from
!!                              which the orchestration runtime will generate new
!!                              tiles.
!!                              Prototype tile wrappers are created by calling
!!                              a function like, for example,
!!                              instantiate_cpu_tf_hydro_wrapper_c in the case
!!                              of orchestrating work for a Hydro operation.
subroutine Orchestration_executeTasks_CpuGpuSplit(MH_pktTaskFunction,  &
                                          MH_tileTaskFunction, &
                                          nDistributorThreads, &
                                          nThreads,            &
                                          nTilesPerPacket,     &
                                          nTilesPerCpuTurn,    &
                                          MH_packet_Cptr,      &
                                          MH_tileProto_Cptr)
    use iso_c_binding, ONLY : C_PTR
    use Orchestration_interfaceTypeDecl, ONLY : milhoja_runtime_taskFunction
    implicit none

    procedure(milhoja_runtime_taskFunction)            :: MH_pktTaskFunction
    procedure(milhoja_runtime_taskFunction)            :: MH_tileTaskFunction
    integer,                                intent(IN) :: nDistributorThreads
    integer,                                intent(IN) :: nThreads
    integer,                                intent(IN) :: nTilesPerPacket
    integer,                                intent(IN) :: nTilesPerCpuTurn
    type(C_PTR),                            intent(IN) :: MH_packet_CPtr
    type(C_PTR),                            intent(IN) :: MH_tileProto_CPtr

end subroutine Orchestration_executeTasks_CpuGpuSplit

