Simulation += sim_inletData.o \
              sim_inletInterface.o \
              sim_inletInit.o \
              sim_inletFinalize.o \
              sim_inletApplyBCToFace.o \
              sim_inletSetForcing.o \
              sim_inletVelBlk.o \
              sim_inletVelBlkPhased.o \
              sim_inletLSDampingBlk.o 
