MoL += ml_interface.o	\
	   ml_init.o		\
	   ml_finalize.o	\
	   ml_advance.o		\
	   ml_error.o		\
	   ml_warn.o		\
	   ml_status.o

MoL += ml_memInterface.o		\
	   ml_memAlloc.o 			\
	   ml_memFree.o				\
	   ml_memGetDataPtr.o		\
	   ml_memReleaseDataPtr.o	\
	   ml_memZero.o				\
	   ml_memCopy.o				\
	   ml_memAddToVars.o
