MoL += ml_interface.o	\
	   ml_init.o		\
	   ml_finalize.o	\
	   ml_advance.o

MoL += ml_memInterface.o	\
	   ml_memAlloc.o 		\
	   ml_memFree.o			\
	   ml_memZero.o			\
	   ml_memCopy.o			\
	   ml_memAddToVars.o
