MoL = MoL_interface.o			\
	  MoL_init.o				\
	  MoL_finalize.o			\
	  MoL_advance.o				\
	  MoL_registerVariable.o	\
	  MoL_registerFunction.o	\
	  MoL_releaseFunctions.o	\
	  MoL_regrid.o					\
	  MoL_getDataPtr.o			\
	  MoL_releaseDataPtr.o
