# Flash-X Makefile header for Aurora
#
# Currently Loaded Modules:
#   1) gcc-runtime/13.3.0-ghotoln (H)   5) gcc/13.3.0                    9) hwloc/2.11.3-mpich-level-zero      13) cray-pals/1.4.0
#   2) gmp/6.3.0-mtokfaw          (H)   6) oneapi/release/2025.0.5      10) yaksa/0.3-7ks5f26             (H)  14) cray-libpals/1.4.0
#   3) mpfr/4.2.1-gkcdl5w         (H)   7) libiconv/1.17-jjpb4sl   (H)  11) mpich/opt/develop-git.6037a7a      15) hdf5/1.14.5
#   4) mpc/1.3.1-rdrlvsl          (H)   8) libxml2/2.13.5               12) libfabric/1.22.0
#
#----------------------------------------------------------------------------
# Set the HDF5/MPI library paths -- these need to be updated for your system
#----------------------------------------------------------------------------

MPI_PATH   =
AMREX_PATH =
HDF5_PATH  = ${HDF5_ROOT}
HYPRE_PATH =
CUDA_PATH  =
MA28_PATH =
MILHOJA_PATH =
BITTREE_PATH =

#----------------------------------------------------------------------------
# Compiler and linker commands
#
#   Use the MPICH wrappers around the compilers -- these will automatically
#   load the proper libraries and include files.  Version of MPICH prior
#   to 1.2.2 (?) do not recognize .F90 as a valid Fortran file extension.
#   You need to edit mpif90 and add .F90 to the test of filename extensions,
#   or upgrade your MPICH.
#----------------------------------------------------------------------------

FCOMP   = mpifort
CCOMP   = mpicc
CPPCOMP = mpicxx -std=c++17
CUCOMP  =
LINK    = mpifort

# pre-processor flag
MDEFS =
PP    = -D

#----------------------------------------------------------------------------
# Compilation flags
#
#  Three sets of compilation/linking flags are defined: one for optimized
#  code, one for testing, and one for debugging.  The default is to use the
#  _OPT version.  Specifying -debug to setup will pick the _DEBUG version,
#  these should enable bounds checking.  Specifying _TEST is used for
#  flash_test, and is set for quick code generation, and (sometimes)
#  profiling.  The Makefile generated by setup will assign the generic token
#  (ex. FFLAGS) to the proper set of flags (ex. FFLAGS_OPT).
#----------------------------------------------------------------------------

OPENMP = -fiopenmp

FFLAGS_AMREX = -I${AMREX_PATH}/include
FFLAGS_HDF5  = -I${HDF5_PATH}/include ${MDEFS}${PP}H5_USE_18_API
FFLAGS_HYPRE = -I${HYPRE_PATH}/include ${FFLAGS_LAPACK}
FFLAGS_OMP_OL= ${OPENMP} -fopenmp-targets=spir64
FFLAGS_MILHOJA = -I${MILHOJA_PATH}/include -recursive -pthread
FFLAGS_MILHOJA_AMREX = -I${MILHOJA_PATH}/include -recursive ${FFLAGS_AMREX} -pthread
FFLAGS_BITTREE = -I${BITTREE_PATH}/include

OPT_FLAGS    = -g -O2
TEST_FLAGS   = -g -O1
DEBUG_FLAGS  = -g -O0

BASE_FFLAGS =

FFLAGS_OPT   = -c ${BASE_FFLAGS} ${OPT_FLAGS}
FFLAGS_TEST  = -c ${BASE_FFLAGS} ${TEST_FLAGS}
FFLAGS_DEBUG = -c ${BASE_FFLAGS} ${DEBUG_FLAGS} -warn all -check all

F90FLAGS     = -r8
f90FLAGS     = ${F90FLAGS}
F77FLAGS     = -r8 -fixed
f77FLAGS     = ${F77FLAGS}

CFLAGS_AMREX = -I${AMREX_PATH}/include
CFLAGS_HDF5  = -I$(HDF5_PATH)/include ${PP}H5_USE_18_API
CFLAGS_HYPRE = -I${HYPRE_PATH}/include ${CFLAGS_LAPACK}
CFLAGS_CUDA  = -I${CUDA_PATH}/include
CFLAGS_OMP_OL= ${OPENMP} -fopenmp-targets=spir64
CFLAGS_MILHOJA = -I${MILHOJA_PATH}/include -pthread
CFLAGS_MILHOJA_AMREX = -I${MILHOJA_PATH}/include ${CFLAGS_AMREX} -pthread
CFLAGS_BITTREE = -I${BITTREE_PATH}/include

CFLAGS_OPT   = -c ${OPT_FLAGS}
CFLAGS_TEST  = -c ${TEST_FLAGS}
CFLAGS_DEBUG = -c ${DEBUG_FLAGS}


.SUFFIXES: .o .c .f .F .h .fh .F90 .f90 .cu

#----------------------------------------------------------------------------
# Linker flags
#----------------------------------------------------------------------------
LFLAGS_OPT   = ${OPT_FLAGS} -o
LFLAGS_TEST  = ${TEST_FLAGS} -o
LFLAGS_DEBUG = ${DEBUG_FLAGS} -g -O0 -o

#----------------------------------------------------------------------------
# Library specific linking
#
#  If a FLASH module has a 'LIBRARY xxx' line in its Config file, we need to
#  create a macro in this Makefile.h for LIB_xxx, which will be added to the
#  link line when FLASH is built.  This allows us to switch between different
#  (incompatible) libraries.  We also create a _OPT, _DEBUG, and _TEST
#  library macro to add any performance-minded libraries (like fast math),
#  depending on how FLASH was setup.
#----------------------------------------------------------------------------

LIB_MPI =

LIB_STDCXX = -lstdc++
LIB_AMREX = -L${AMREX_PATH}/lib -lamrex -lstdc++
LIB_HDF5  = -L${HDF5_PATH}/lib -lhdf5 -lhdf5_fortran
LIB_HYPRE = -L${HYPRE_PATH}/lib -lHYPRE ${LIB_LAPACK}
LIB_OMP_OL= ${OPENMP} -fopenmp-targets=spir64
LIB_MA28  = -L${MA28_PATH} -lma28
LIB_MILHOJA = -pthread -L${MILHOJA_PATH}/lib -lmilhoja
LIB_MILHOJA_AMREX = -pthread -L${MILHOJA_PATH}/lib -lmilhoja ${LIB_AMREX}
LIB_BITTREE = -L${BITTREE_PATH}/lib -lbittree

LIB_OPT   =
LIB_DEBUG =
LIB_TEST  =

LIB_LAPACK = -llapack -lblas

#----------------------------------------------------------------------------
# Additional machine-dependent object files
#
#  Add any machine specific files here -- they will be compiled and linked
#  when FLASH is built.
#----------------------------------------------------------------------------

MACHOBJ =

#----------------------------------------------------------------------------
# Additional commands
#----------------------------------------------------------------------------

MV = mv -f
AR = ar -r
RM = rm -f
CD = cd
RL = ranlib
ECHO = echo
AWK = awk
CAT = cat
