#	Makefile for the burning networks
# [/source/physics/sourceTerms/Burn/network]

Burn += bnIntegrate_interface.o bn_netIntegrate.o \
				bn_baderMa28.o bn_baderGift.o \
				bn_rosenMa28.o bn_rosenGift.o \
				bn_pzExtr.o

