# Makefile for source/Simulations/setups/Cellular

Simulation += Simulation_data.o sim_ranmar.o sim_local_interface.o sim_find_ign_state_keeping_pres.o
Simulation_init.o : Simulation_data.o
Simulation_initBlock.o : Simulation_data.o

