#[ for Simulation/SimulationMain/unitTest/Gravity/GravityMain/unitTest/Poisson3]

Grid += gr_mpoleInterface.o gr_mpoleMoments.o gr_mpoleMomBins3Dspherical.o gr_mpoleMom3Dspherical.o gr_mpolePot3Dspherical.o gr_mpoleRad3Dspherical.o gr_mpoleCen3Dspherical.o #faceareaStore.o check_variable_sneo.o
Simulation += Simulation_data.o sim_analytical.o

