Simulation += sim_heaterInterface.o \
              sim_heaterInit.o \
              sim_heaterFinalize.o \
              sim_heaterRead.o \
              sim_heaterLSReInit.o \
              sim_heaterCheckSites.o \
              sim_heaterInitBlk.o \
              sim_heaterLSReInitBlk.o \
              sim_heaterCheckSitesBlk.o \
              sim_heaterApplyBCToRegion.o \
              sim_heaterTagSites.o

Simulation += sim_inletInterface.o \
              sim_inletInit.o \
              sim_inletFinalize.o \
              sim_inletApplyBCToRegion.o

Simulation += sim_outletInterface.o \
              sim_outletInit.o \
              sim_outletFinalize.o \
              sim_outletSetForcing.o \
              sim_outletLSDamping.o \
              sim_outletVelFrc.o \
              sim_outletVelFrcPhased.o \
              sim_outletApplyBCToRegion.o
