[dr_iter_getBaseVals]
definition =
 call itor%%currentTile(tileDesc)
         call tileDesc%%deltas(del)
         nullify(solnData)
         call tileDesc%%getDataPtr(solnData, CENTER)
         blkLimits=tileDesc%%limits
	 blkLimitsGC=tileDesc%%blkLimitsGC

[dr_getFacePnt]
definition=
         nullify(facexData, faceyData, facezData)
         call tileDesc%%getDataPtr(facexData, FACEX)
         call tileDesc%%getDataPtr(faceyData, FACEY)
 #if NDIM == 3
         call tileDesc%%getDataPtr(facezData, FACEZ)
 #endif


[dr_iter_releaseBase]
definition =
         call tileDesc%%releaseDataPtr(solnData, CENTER)
         call itor%%next()


[dr_releaseFacePnt]
definition = 
        call tileDesc%%releaseDataPtr(facexData, FACEX)
         call tileDesc%%releaseDataPtr(faceyData, FACEY)
 #if NDIM ==3
         call tileDesc%%releaseDataPtr(facezData, FACEZ)
 #endif
         !---------------------------------------------------------

[dr_mapLimits]
definition =
  lo(:) = blkLimits(LOW,:)-blkLimitsGC(LOW,:)+1
  hi(:) = blkLimits(HIGH,:)-blkLimits(LOW,:)+lo(:)

[dr_mapLimitsGC]
definition =
  logc(:) = 1
  higc(:) = blkLimitsGC(HIGH,:)-blkLimitsGC(LOW,:)+logc(:)


[dr_getCoords]
definition =
   @M dr_mapLimitsGC
   allocate(xC(higc(IAXIS)))
   xC=0.0
   call Grid_getCellCoords(IAXIS, CENTER, tileDesc%%level,&
                           blkLimitsGC(LOW,IAXIS),blkLimitsGC(HIGH,IAXIS),xC)
   allocate(yC(higc(JAXIS)))
   call Grid_getCellCoords(JAXIS, CENTER, tileDesc%%level,&
                           blkLimitsGC(LOW,JAXIS),blkLimitsGC(HIGH,JAXIS),yC)
 #if NDIM==MDIM
   allocate(zC(higc(KAXIS)))
   call Grid_getCellCoords(KAXIS, CENTER, tileDesc%%level,&
                           blkLimitsGC(LOW,KAXIS),blkLimitsGC(HIGH,KAXIS),zC)
 #endif

[dr_releaseCoords]
definition =
  deallocate(xC); deallocate(yC)
  if(allocated(zC))deallocate(zC)



 