#	Makefile for the FLASH code (equation of state module)

Eos = Eos_wrapped.o Eos.o Eos_init.o Eos_finalize.o Eos_guardCells.o Eos_getParameters.o Eos_interface.o Eos_getAbarZbar.o \
	Eos_sendOutputData.o
