#  Makefile for setup Stir

Simulation += Simulation_data.o

Simulation_initBlock.o : Simulation_data.o Driver_data.o Grid_tile.o Eos_interface.o
Simulation_init.o : Simulation_data.o Driver_data.o RuntimeParameters_interface.o
