IncompNS += IncompNS_interface.o \
	    IncompNS.o IncompNS_init.o \
	    IncompNS_sendOutputData.o \
            IncompNS_computeDt.o \
	    IncompNS_finalize.o \
            IncompNS_velomgToCenter.o \
            IncompNS_stats.o \
            IncompNS_statsIOExport.o \
            IncompNS_getScalarProp.o \
            IncompNS_getGridVar.o \
            IncompNS_getVectorProp.o \
            IncompNS_setVectorProp.o \
            IncompNS_advection.o \
            IncompNS_diffusion.o \
            IncompNS_predictor.o \
            IncompNS_divergence.o \
            IncompNS_solvePoisson.o \
            IncompNS_corrector.o \
            IncompNS_indicators.o \
            IncompNS_reInitGridVars.o

