Spacetime = Spacetime_interface.o \
				Spacetime_init.o \
				Spacetime_finalize.o \
				Spacetime.o \
				Spacetime_computeDt.o \
				Spacetime_getLapse.o \
				Spacetime_getShift.o \
				Spacetime_getMetric.o \
				Spacetime_getCurvature.o \
				Spacetime_addToStressEnergyTensor.o \
				Spacetime_applyHamiltonianConstraint.o \
				Spacetime_applyMomentumConstraint.o \
				Spacetime_molExplicitRHS.o \
				Spacetime_molExplicitRHS_tile.o \
				Spacetime_molFastRHS.o \
				Spacetime_molFastRHS_tile.o \
				Spacetime_molPreEvolve.o \
				Spacetime_molPostUpdate.o \
				Spacetime_molPostFastUpdate.o \
				Spacetime_molPostTimeStep.o \
				Spacetime_molPostRegrid.o \
				Spacetime_unitTest.o
