!----------------------------------------------------------------------
!!  Licensed under the Apache License, Version 2.0 (the "License");
!!  you may not use this file except in compliance with the License.
!! 
!! Unless required by applicable law or agreed to in writing, software
!! distributed under the License is distributed on an "AS IS" BASIS,
!! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
!! See the License for the specific language governing permissions and
!! limitations under the License.
! PARAMESH - an adaptive mesh library.
! Copyright (C) 2003
!
! Use of the PARAMESH software is governed by the terms of the
! usage agreement which can be found in the file
! 'PARAMESH_USERS_AGREEMENT' in the main paramesh directory.
!----------------------------------------------------------------------

!
! These are wrapper routines for some mpi calls. We need these to avoid an error
! message generated by the NAG F95 compiler, when the mpi routines are called for
! different datatypes within the same calling routine.
!


! Reduction operations


       subroutine mpi_dble_allreduce(sendbuf,recvbuf,count,datatype, & 
     &                               op,comm,ierror)
       double precision    :: sendbuf(*),recvbuf(*)
       integer             :: count,datatype,op,comm,ierror

       call mpi_allreduce(sendbuf,recvbuf,count,datatype, & 
     &                    op,comm,ierror)

       return
       end subroutine mpi_dble_allreduce


